[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/herbs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"